# Generated by Django 2.2 on 2019-05-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190513_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'My image', 'verbose_name_plural': 'My images'},
        ),
    ]
